--  Configuration for light_tasking_stm32f746 generated by Alire
pragma Restrictions (No_Elaboration_Code);
pragma Style_Checks (Off);

package Light_Tasking_Stm32f746_Config is
   pragma Pure;

   Crate_Version : constant String := "15.0.0-dev";
   Crate_Name : constant String := "light_tasking_stm32f746";

   Alire_Host_OS : constant String := "linux";

   Alire_Host_Arch : constant String := "x86_64";

   Alire_Host_Distro : constant String := "ubuntu";

   type PLL_Src_Kind is (HSE, HSI);
   PLL_Src : constant PLL_Src_Kind := HSI;

   HSE_Bypass : constant Boolean := False;

   PLL_Q_Enable : constant Boolean := True;

   LSE_Enabled : constant Boolean := False;

   Interrupt_Stack_Size_First : constant :=  1;
   Interrupt_Stack_Size_Last : constant :=  9223372036854775807;
   Interrupt_Stack_Size : constant :=  1024;

   HSE_Clock_Frequency_First : constant :=  4000000;
   HSE_Clock_Frequency_Last : constant :=  26000000;
   HSE_Clock_Frequency : constant :=  8000000;

   type PLL_P_Div_Kind is (DIV2, DIV4, DIV6, DIV8);
   PLL_P_Div : constant PLL_P_Div_Kind := DIV2;

   PLL_M_Div_First : constant :=  2;
   PLL_M_Div_Last : constant :=  63;
   PLL_M_Div : constant :=  16;

   type APB2_Pre_Kind is (DIV1, DIV2, DIV4, DIV8, DIV16);
   APB2_Pre : constant APB2_Pre_Kind := DIV2;

   type APB1_Pre_Kind is (DIV1, DIV2, DIV4, DIV8, DIV16);
   APB1_Pre : constant APB1_Pre_Kind := DIV4;

   Interrupt_Secondary_Stack_Size_First : constant :=  1;
   Interrupt_Secondary_Stack_Size_Last : constant :=  9223372036854775807;
   Interrupt_Secondary_Stack_Size : constant :=  128;

   type AHB_Pre_Kind is (DIV1, DIV2, DIV4, DIV8, DIV16, DIV64, DIV128, DIV256, DIV512);
   AHB_Pre : constant AHB_Pre_Kind := DIV1;

   PLL_Q_Div_First : constant :=  2;
   PLL_Q_Div_Last : constant :=  15;
   PLL_Q_Div : constant :=  9;

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := development;

   PLL_N_Mul_First : constant :=  50;
   PLL_N_Mul_Last : constant :=  432;
   PLL_N_Mul : constant :=  432;

   LSE_Bypass : constant Boolean := False;

   LSI_Enabled : constant Boolean := True;

   type SYSCLK_Src_Kind is (HSI, HSE, PLLCLK);
   SYSCLK_Src : constant SYSCLK_Src_Kind := PLLCLK;

end Light_Tasking_Stm32f746_Config;
